services:
    isir:
        image: ghcr.io/yassinebenh/isir:latest
        restart: unless-stopped
        ports:
            - '8080:8080'
        volumes:
            - isir_data:/var/www/html/storage

volumes:
    isir_data:
